<a href="https://colab.research.google.com/github/Bateyjosue/NLP_Fellowship/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## In-class Practicals

Convert this into a class and functions:


In [2]:
import numpy as np

In [1]:
class Bow:
    def __init__(self):
        # Enter code here
        self.vocab = {}


    def fit(self,document):
        #Enter code
        text = ' '.join(document).split()
        text = list(set(text))
        for key, txt in enumerate(text):
            self.vocab[txt] = key 

    def transform(self,data):
        
        #Enter code
        transformed = np.empty((len(data), len(self.vocab))) 
        for row, sentence in enumerate(data):
            transforme = np.zeros(len(self.vocab))
            for word in sentence.split():
                if word in self.vocab:
                    index = self.vocab[word]
                    transforme[index] += 1
            transformed[row] = transforme
        return transformed

    def fit_transform(self,data):
        self.fit(data)
        return self.transform(data)

    def _transform_single(self,list_words):

        # This code is for transforming a single sentence
        transformed = np.zeros(len(self.vocab))
        for word in list_words.split():
            if word in self.vocab:
                index = self.vocab[word]
                transformed[index] += 1
        return transformed

In [7]:
bow = Bow()
data = ['this is a list of sentences example', 'second sentence in list of sentence', 'a word for complexity',]
test_sentence = 'this is an example of sentence with sentence that are complexity with many example'
bow.fit(data)
print(f'VOCAB: {bow.vocab}')
fq = bow.fit_transform(data)
print(fq)

fq_single = bow._transform_single(test_sentence)
fq_single

VOCAB: {'list': 0, 'complexity': 1, 'this': 2, 'is': 3, 'word': 4, 'sentence': 5, 'second': 6, 'of': 7, 'in': 8, 'for': 9, 'a': 10, 'example': 11, 'sentences': 12}
[[1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1.]
 [1. 0. 0. 0. 0. 2. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.]]


array([0., 1., 1., 1., 0., 2., 0., 1., 0., 0., 0., 2., 0.])

**`!Note`**
We compare the **vocab** which is our unique dictonary of words/Tokens to the **test sentence** given to check the token at a specific index occur how many time in the sentence . . .

    VOCAB: {
        'list': 0, 
        'complexity': 1, 
        'this': 2, 
        'is': 3, 
        'word': 4, 
        'sentence': 5, 
        'second': 6, 
        'of': 7, 
        'in': 8, 
        'for': 9, 
        'a': 10, 
        'example': 11, 
        'sentences': 12
    }


1.   ### List of sentences Test
          [
            [1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1.]
            [1. 0. 0. 0. 0. 2. 1. 1. 1. 0. 0. 0. 0.]
            [0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0.]
          ]

2.    ### Single sentence Test

**Sentence:** 'this is an example of sentence with sentence that are complexity with many example'

      array([0., 1., 1., 1., 0., 2., 0., 1., 0., 0., 0., 2., 0.])


## Assignment
BOW using your tokens and share some sentences to text